spring:
  application:
    name: feign-rest-consumer

server.port: 8080

# Eureka config:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck.enabled: true

# Hystrix config:
feign.hystrix.enabled: true

# This parameter defines timeout for whole request (including time waiting in the tasks queue if all threads in threadpool are busy)
# For more details see https://cloud.spring.io/spring-cloud-netflix/multi/multi__hystrix_timeouts_and_ribbon_clients.html
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 4000

hystrix:
  threadpool:
    default:
      coreSize: 2
      # This setting only takes effect if you also set allowMaximumSizeToDivergeFromCoreSize=true.
      # Note: in the current implementation (version 1.5.12) of HystrixThreadPoolDefault maximumSize have effect only if maxQueueSize=-1.
      maximumSize: 3
      allowMaximumSizeToDivergeFromCoreSize: true
      # If coreSize < maximumSize, then this property controls how long a thread will go unused before being released
      keepAliveTimeMinutes: 2
      maxQueueSize: -1
      # Note: Property 'queueSizeRejectionThreshold' doesn't have effect if maxQueueSize=-1
      queueSizeRejectionThreshold: 5

# Ribbon config:
ribbon:
  # This parameter defines timeout for direct call to thirdparty service (ignoring time waiting in tasks queue)
  ReadTimeout: 3100

# Use "*" to expose all endpoints, or a comma-separated list to expose selected ones
# Actuator configuration to exposure /actuator/hystrix.stream, /actuator/info, /actuator/health, /actuator/env
management.endpoints.web.exposure.include: hystrix.stream, info, health, env
