spring.application.name: CONFIGURATION-SERVICE
server.port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VolodymyrShpynta/spring-cloud-sample
          searchPaths: /spring-cloud-config-server/config-repo/,/spring-cloud-config-server/config-repo/{application}
          skipSslValidation: true
          clone-on-start: true
  security:
    user:
      name: root
      password: s3cr3t

# Eureka config:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck.enabled: true